### ISSUE TITLE
Can't install mod from Paradox Mods

### ISSUE THREAD

**Issue by ghost** [OldEnt/stellaris-habitat-start-amaryllis#5] opened 2021-08-23 21:17 UTC
Hi,

I am trying to install the mod from https://mods.paradoxplaza.com/mods/3790/Any and it says install of mod failed. Using Stellaris 3.0.4 on Linux.

**Comment by OldEnt** [comment] 2021-08-29 09:19
Thank you for bringing this to my attention. I just tried and I cannot even install the mod on my own Windows machine, but I can do so with my other mod on PDX Mods. Reuploading did not help. PDX Mods being "useful" as usual. Last time I had to remove link to PDX forums from the PDX FORUMS LINK FIELD just to be able to update the mod.

I always update my mods on GitHub. Use the green Code button and download a zip of the mod. Unpack mod contents to [wherever local mod directory is on Linux ](https://stellaris.paradoxwikis.com/Mods)and use [Irony Mod Manager](https://bcssov.github.io/IronyModManager/) to install it.

FYI You can use online tool to download Steam Workshop mods and then install them via Irony Mod Manager, or fully manually.

**Comment by OldEnt** [comment] 2021-09-19 16:36
Paradox support was able to replicate the issue but they won't be fixing it.

Use manual download button or Steam Workshop, I will still be uploading to Paradox Mods. Irony Mod Manager can be useful.

**Closed as completed by OldEnt** 2021-09-19 16:36 UTC

**Comment by TheSiege** [comment] 2021-09-20 03:25
The Irony Mod Manager works fine, thanks for the Info!
I am a bit suprised though that they won't fix a reproduceable bug. Is it hard to fix or linux specific?

**Comment by OldEnt** [comment] 2021-09-29 09:56
This seems to be independent of system, I can't install this mod of mine on my Windows machine either. Fault is either on Paradox Mods page or the Paradox Launcher. I suppose I could reupload the mod...
